// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: metrics.proto
// Protobuf Java Version: 4.28.3

package com.vlad.metrics.models;

public interface CpuMetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vlad.metrics.models.CpuMetric)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double totalLoad = 1;</code>
   * @return The totalLoad.
   */
  double getTotalLoad();

  /**
   * <code>repeated double coreLoads = 2;</code>
   * @return A list containing the coreLoads.
   */
  java.util.List<java.lang.Double> getCoreLoadsList();
  /**
   * <code>repeated double coreLoads = 2;</code>
   * @return The count of coreLoads.
   */
  int getCoreLoadsCount();
  /**
   * <code>repeated double coreLoads = 2;</code>
   * @param index The index of the element to return.
   * @return The coreLoads at the given index.
   */
  double getCoreLoads(int index);

  /**
   * <code>repeated int64 frequency = 3;</code>
   * @return A list containing the frequency.
   */
  java.util.List<java.lang.Long> getFrequencyList();
  /**
   * <code>repeated int64 frequency = 3;</code>
   * @return The count of frequency.
   */
  int getFrequencyCount();
  /**
   * <code>repeated int64 frequency = 3;</code>
   * @param index The index of the element to return.
   * @return The frequency at the given index.
   */
  long getFrequency(int index);
}
