// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: metrics.proto
// Protobuf Java Version: 4.28.3

package com.vlad.metrics.models;

public interface MemoryMetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vlad.metrics.models.MemoryMetric)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 totalPhysicalMemory = 1;</code>
   * @return The totalPhysicalMemory.
   */
  long getTotalPhysicalMemory();

  /**
   * <code>int64 usedPhysicalMemory = 2;</code>
   * @return The usedPhysicalMemory.
   */
  long getUsedPhysicalMemory();

  /**
   * <code>int64 totalSwapMemory = 3;</code>
   * @return The totalSwapMemory.
   */
  long getTotalSwapMemory();

  /**
   * <code>int64 usedSwapMemory = 4;</code>
   * @return The usedSwapMemory.
   */
  long getUsedSwapMemory();

  /**
   * <code>int64 virtualMemoryUsed = 5;</code>
   * @return The virtualMemoryUsed.
   */
  long getVirtualMemoryUsed();
}
