// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: metrics.proto
// Protobuf Java Version: 4.28.3

package com.vlad.metrics.models;

/**
 * Protobuf type {@code com.vlad.metrics.models.OsMetric}
 */
public final class OsMetric extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.vlad.metrics.models.OsMetric)
    OsMetricOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      OsMetric.class.getName());
  }
  // Use OsMetric.newBuilder() to construct.
  private OsMetric(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private OsMetric() {
    osName_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Metrics.internal_static_metrics_OsMetric_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Metrics.internal_static_metrics_OsMetric_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            OsMetric.class, OsMetric.Builder.class);
  }

  public static final int OS_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object osName_ = "";
  /**
   * <code>string os_name = 1;</code>
   * @return The osName.
   */
  @java.lang.Override
  public java.lang.String getOsName() {
    java.lang.Object ref = osName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      osName_ = s;
      return s;
    }
  }
  /**
   * <code>string os_name = 1;</code>
   * @return The bytes for osName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOsNameBytes() {
    java.lang.Object ref = osName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      osName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPTIME_FIELD_NUMBER = 2;
  private long uptime_ = 0L;
  /**
   * <code>int64 uptime = 2;</code>
   * @return The uptime.
   */
  @java.lang.Override
  public long getUptime() {
    return uptime_;
  }

  public static final int PROCESSES_FIELD_NUMBER = 3;
  private int processes_ = 0;
  /**
   * <code>int32 processes = 3;</code>
   * @return The processes.
   */
  @java.lang.Override
  public int getProcesses() {
    return processes_;
  }

  public static final int THREADS_FIELD_NUMBER = 4;
  private int threads_ = 0;
  /**
   * <code>int32 threads = 4;</code>
   * @return The threads.
   */
  @java.lang.Override
  public int getThreads() {
    return threads_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(osName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, osName_);
    }
    if (uptime_ != 0L) {
      output.writeInt64(2, uptime_);
    }
    if (processes_ != 0) {
      output.writeInt32(3, processes_);
    }
    if (threads_ != 0) {
      output.writeInt32(4, threads_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(osName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, osName_);
    }
    if (uptime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, uptime_);
    }
    if (processes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, processes_);
    }
    if (threads_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, threads_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof OsMetric)) {
      return super.equals(obj);
    }
    OsMetric other = (OsMetric) obj;

    if (!getOsName()
        .equals(other.getOsName())) return false;
    if (getUptime()
        != other.getUptime()) return false;
    if (getProcesses()
        != other.getProcesses()) return false;
    if (getThreads()
        != other.getThreads()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OS_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getOsName().hashCode();
    hash = (37 * hash) + UPTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUptime());
    hash = (37 * hash) + PROCESSES_FIELD_NUMBER;
    hash = (53 * hash) + getProcesses();
    hash = (37 * hash) + THREADS_FIELD_NUMBER;
    hash = (53 * hash) + getThreads();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static OsMetric parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static OsMetric parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static OsMetric parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static OsMetric parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static OsMetric parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static OsMetric parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static OsMetric parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static OsMetric parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static OsMetric parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static OsMetric parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static OsMetric parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static OsMetric parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(OsMetric prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.vlad.metrics.models.OsMetric}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.vlad.metrics.models.OsMetric)
          OsMetricOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Metrics.internal_static_metrics_OsMetric_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Metrics.internal_static_metrics_OsMetric_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OsMetric.class, OsMetric.Builder.class);
    }

    // Construct using com.vlad.metrics.models.OsMetric.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      osName_ = "";
      uptime_ = 0L;
      processes_ = 0;
      threads_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Metrics.internal_static_metrics_OsMetric_descriptor;
    }

    @java.lang.Override
    public OsMetric getDefaultInstanceForType() {
      return OsMetric.getDefaultInstance();
    }

    @java.lang.Override
    public OsMetric build() {
      OsMetric result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public OsMetric buildPartial() {
      OsMetric result = new OsMetric(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(OsMetric result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.osName_ = osName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.uptime_ = uptime_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.processes_ = processes_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.threads_ = threads_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof OsMetric) {
        return mergeFrom((OsMetric)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(OsMetric other) {
      if (other == OsMetric.getDefaultInstance()) return this;
      if (!other.getOsName().isEmpty()) {
        osName_ = other.osName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getUptime() != 0L) {
        setUptime(other.getUptime());
      }
      if (other.getProcesses() != 0) {
        setProcesses(other.getProcesses());
      }
      if (other.getThreads() != 0) {
        setThreads(other.getThreads());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              osName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              uptime_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              processes_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              threads_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object osName_ = "";
    /**
     * <code>string os_name = 1;</code>
     * @return The osName.
     */
    public java.lang.String getOsName() {
      java.lang.Object ref = osName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        osName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string os_name = 1;</code>
     * @return The bytes for osName.
     */
    public com.google.protobuf.ByteString
        getOsNameBytes() {
      java.lang.Object ref = osName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string os_name = 1;</code>
     * @param value The osName to set.
     * @return This builder for chaining.
     */
    public Builder setOsName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      osName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string os_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOsName() {
      osName_ = getDefaultInstance().getOsName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string os_name = 1;</code>
     * @param value The bytes for osName to set.
     * @return This builder for chaining.
     */
    public Builder setOsNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      osName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long uptime_ ;
    /**
     * <code>int64 uptime = 2;</code>
     * @return The uptime.
     */
    @java.lang.Override
    public long getUptime() {
      return uptime_;
    }
    /**
     * <code>int64 uptime = 2;</code>
     * @param value The uptime to set.
     * @return This builder for chaining.
     */
    public Builder setUptime(long value) {

      uptime_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 uptime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUptime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      uptime_ = 0L;
      onChanged();
      return this;
    }

    private int processes_ ;
    /**
     * <code>int32 processes = 3;</code>
     * @return The processes.
     */
    @java.lang.Override
    public int getProcesses() {
      return processes_;
    }
    /**
     * <code>int32 processes = 3;</code>
     * @param value The processes to set.
     * @return This builder for chaining.
     */
    public Builder setProcesses(int value) {

      processes_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 processes = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProcesses() {
      bitField0_ = (bitField0_ & ~0x00000004);
      processes_ = 0;
      onChanged();
      return this;
    }

    private int threads_ ;
    /**
     * <code>int32 threads = 4;</code>
     * @return The threads.
     */
    @java.lang.Override
    public int getThreads() {
      return threads_;
    }
    /**
     * <code>int32 threads = 4;</code>
     * @param value The threads to set.
     * @return This builder for chaining.
     */
    public Builder setThreads(int value) {

      threads_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 threads = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearThreads() {
      bitField0_ = (bitField0_ & ~0x00000008);
      threads_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.vlad.metrics.models.OsMetric)
  }

  // @@protoc_insertion_point(class_scope:com.vlad.metrics.models.OsMetric)
  private static final OsMetric DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new OsMetric();
  }

  public static OsMetric getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OsMetric>
      PARSER = new com.google.protobuf.AbstractParser<OsMetric>() {
    @java.lang.Override
    public OsMetric parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OsMetric> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OsMetric> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public OsMetric getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

