// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: metrics.proto
// Protobuf Java Version: 4.28.3

package metrics;

/**
 * Protobuf type {@code com.vlad.metrics.models.MemoryMetric}
 */
public final class MemoryMetric extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.vlad.metrics.models.MemoryMetric)
    MemoryMetricOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      MemoryMetric.class.getName());
  }
  // Use MemoryMetric.newBuilder() to construct.
  private MemoryMetric(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MemoryMetric() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return metrics.Metrics.internal_static_metrics_MemoryMetric_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return metrics.Metrics.internal_static_metrics_MemoryMetric_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            metrics.MemoryMetric.class, metrics.MemoryMetric.Builder.class);
  }

  public static final int TOTALPHYSICALMEMORY_FIELD_NUMBER = 1;
  private long totalPhysicalMemory_ = 0L;
  /**
   * <code>int64 totalPhysicalMemory = 1;</code>
   * @return The totalPhysicalMemory.
   */
  @java.lang.Override
  public long getTotalPhysicalMemory() {
    return totalPhysicalMemory_;
  }

  public static final int USEDPHYSICALMEMORY_FIELD_NUMBER = 2;
  private long usedPhysicalMemory_ = 0L;
  /**
   * <code>int64 usedPhysicalMemory = 2;</code>
   * @return The usedPhysicalMemory.
   */
  @java.lang.Override
  public long getUsedPhysicalMemory() {
    return usedPhysicalMemory_;
  }

  public static final int TOTALSWAPMEMORY_FIELD_NUMBER = 3;
  private long totalSwapMemory_ = 0L;
  /**
   * <code>int64 totalSwapMemory = 3;</code>
   * @return The totalSwapMemory.
   */
  @java.lang.Override
  public long getTotalSwapMemory() {
    return totalSwapMemory_;
  }

  public static final int USEDSWAPMEMORY_FIELD_NUMBER = 4;
  private long usedSwapMemory_ = 0L;
  /**
   * <code>int64 usedSwapMemory = 4;</code>
   * @return The usedSwapMemory.
   */
  @java.lang.Override
  public long getUsedSwapMemory() {
    return usedSwapMemory_;
  }

  public static final int VIRTUALMEMORYUSED_FIELD_NUMBER = 5;
  private long virtualMemoryUsed_ = 0L;
  /**
   * <code>int64 virtualMemoryUsed = 5;</code>
   * @return The virtualMemoryUsed.
   */
  @java.lang.Override
  public long getVirtualMemoryUsed() {
    return virtualMemoryUsed_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (totalPhysicalMemory_ != 0L) {
      output.writeInt64(1, totalPhysicalMemory_);
    }
    if (usedPhysicalMemory_ != 0L) {
      output.writeInt64(2, usedPhysicalMemory_);
    }
    if (totalSwapMemory_ != 0L) {
      output.writeInt64(3, totalSwapMemory_);
    }
    if (usedSwapMemory_ != 0L) {
      output.writeInt64(4, usedSwapMemory_);
    }
    if (virtualMemoryUsed_ != 0L) {
      output.writeInt64(5, virtualMemoryUsed_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (totalPhysicalMemory_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, totalPhysicalMemory_);
    }
    if (usedPhysicalMemory_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, usedPhysicalMemory_);
    }
    if (totalSwapMemory_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, totalSwapMemory_);
    }
    if (usedSwapMemory_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, usedSwapMemory_);
    }
    if (virtualMemoryUsed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, virtualMemoryUsed_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof metrics.MemoryMetric)) {
      return super.equals(obj);
    }
    metrics.MemoryMetric other = (metrics.MemoryMetric) obj;

    if (getTotalPhysicalMemory()
        != other.getTotalPhysicalMemory()) return false;
    if (getUsedPhysicalMemory()
        != other.getUsedPhysicalMemory()) return false;
    if (getTotalSwapMemory()
        != other.getTotalSwapMemory()) return false;
    if (getUsedSwapMemory()
        != other.getUsedSwapMemory()) return false;
    if (getVirtualMemoryUsed()
        != other.getVirtualMemoryUsed()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTALPHYSICALMEMORY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalPhysicalMemory());
    hash = (37 * hash) + USEDPHYSICALMEMORY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUsedPhysicalMemory());
    hash = (37 * hash) + TOTALSWAPMEMORY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalSwapMemory());
    hash = (37 * hash) + USEDSWAPMEMORY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUsedSwapMemory());
    hash = (37 * hash) + VIRTUALMEMORYUSED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVirtualMemoryUsed());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static metrics.MemoryMetric parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static metrics.MemoryMetric parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static metrics.MemoryMetric parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static metrics.MemoryMetric parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static metrics.MemoryMetric parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static metrics.MemoryMetric parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static metrics.MemoryMetric parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static metrics.MemoryMetric parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static metrics.MemoryMetric parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static metrics.MemoryMetric parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static metrics.MemoryMetric parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static metrics.MemoryMetric parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(metrics.MemoryMetric prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.vlad.metrics.models.MemoryMetric}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.vlad.metrics.models.MemoryMetric)
      metrics.MemoryMetricOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return metrics.Metrics.internal_static_metrics_MemoryMetric_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return metrics.Metrics.internal_static_metrics_MemoryMetric_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              metrics.MemoryMetric.class, metrics.MemoryMetric.Builder.class);
    }

    // Construct using com.vlad.metrics.models.MemoryMetric.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      totalPhysicalMemory_ = 0L;
      usedPhysicalMemory_ = 0L;
      totalSwapMemory_ = 0L;
      usedSwapMemory_ = 0L;
      virtualMemoryUsed_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return metrics.Metrics.internal_static_metrics_MemoryMetric_descriptor;
    }

    @java.lang.Override
    public metrics.MemoryMetric getDefaultInstanceForType() {
      return metrics.MemoryMetric.getDefaultInstance();
    }

    @java.lang.Override
    public metrics.MemoryMetric build() {
      metrics.MemoryMetric result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public metrics.MemoryMetric buildPartial() {
      metrics.MemoryMetric result = new metrics.MemoryMetric(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(metrics.MemoryMetric result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.totalPhysicalMemory_ = totalPhysicalMemory_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.usedPhysicalMemory_ = usedPhysicalMemory_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.totalSwapMemory_ = totalSwapMemory_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.usedSwapMemory_ = usedSwapMemory_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.virtualMemoryUsed_ = virtualMemoryUsed_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof metrics.MemoryMetric) {
        return mergeFrom((metrics.MemoryMetric)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(metrics.MemoryMetric other) {
      if (other == metrics.MemoryMetric.getDefaultInstance()) return this;
      if (other.getTotalPhysicalMemory() != 0L) {
        setTotalPhysicalMemory(other.getTotalPhysicalMemory());
      }
      if (other.getUsedPhysicalMemory() != 0L) {
        setUsedPhysicalMemory(other.getUsedPhysicalMemory());
      }
      if (other.getTotalSwapMemory() != 0L) {
        setTotalSwapMemory(other.getTotalSwapMemory());
      }
      if (other.getUsedSwapMemory() != 0L) {
        setUsedSwapMemory(other.getUsedSwapMemory());
      }
      if (other.getVirtualMemoryUsed() != 0L) {
        setVirtualMemoryUsed(other.getVirtualMemoryUsed());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              totalPhysicalMemory_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              usedPhysicalMemory_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              totalSwapMemory_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              usedSwapMemory_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              virtualMemoryUsed_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long totalPhysicalMemory_ ;
    /**
     * <code>int64 totalPhysicalMemory = 1;</code>
     * @return The totalPhysicalMemory.
     */
    @java.lang.Override
    public long getTotalPhysicalMemory() {
      return totalPhysicalMemory_;
    }
    /**
     * <code>int64 totalPhysicalMemory = 1;</code>
     * @param value The totalPhysicalMemory to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPhysicalMemory(long value) {

      totalPhysicalMemory_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 totalPhysicalMemory = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalPhysicalMemory() {
      bitField0_ = (bitField0_ & ~0x00000001);
      totalPhysicalMemory_ = 0L;
      onChanged();
      return this;
    }

    private long usedPhysicalMemory_ ;
    /**
     * <code>int64 usedPhysicalMemory = 2;</code>
     * @return The usedPhysicalMemory.
     */
    @java.lang.Override
    public long getUsedPhysicalMemory() {
      return usedPhysicalMemory_;
    }
    /**
     * <code>int64 usedPhysicalMemory = 2;</code>
     * @param value The usedPhysicalMemory to set.
     * @return This builder for chaining.
     */
    public Builder setUsedPhysicalMemory(long value) {

      usedPhysicalMemory_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 usedPhysicalMemory = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsedPhysicalMemory() {
      bitField0_ = (bitField0_ & ~0x00000002);
      usedPhysicalMemory_ = 0L;
      onChanged();
      return this;
    }

    private long totalSwapMemory_ ;
    /**
     * <code>int64 totalSwapMemory = 3;</code>
     * @return The totalSwapMemory.
     */
    @java.lang.Override
    public long getTotalSwapMemory() {
      return totalSwapMemory_;
    }
    /**
     * <code>int64 totalSwapMemory = 3;</code>
     * @param value The totalSwapMemory to set.
     * @return This builder for chaining.
     */
    public Builder setTotalSwapMemory(long value) {

      totalSwapMemory_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 totalSwapMemory = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalSwapMemory() {
      bitField0_ = (bitField0_ & ~0x00000004);
      totalSwapMemory_ = 0L;
      onChanged();
      return this;
    }

    private long usedSwapMemory_ ;
    /**
     * <code>int64 usedSwapMemory = 4;</code>
     * @return The usedSwapMemory.
     */
    @java.lang.Override
    public long getUsedSwapMemory() {
      return usedSwapMemory_;
    }
    /**
     * <code>int64 usedSwapMemory = 4;</code>
     * @param value The usedSwapMemory to set.
     * @return This builder for chaining.
     */
    public Builder setUsedSwapMemory(long value) {

      usedSwapMemory_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 usedSwapMemory = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsedSwapMemory() {
      bitField0_ = (bitField0_ & ~0x00000008);
      usedSwapMemory_ = 0L;
      onChanged();
      return this;
    }

    private long virtualMemoryUsed_ ;
    /**
     * <code>int64 virtualMemoryUsed = 5;</code>
     * @return The virtualMemoryUsed.
     */
    @java.lang.Override
    public long getVirtualMemoryUsed() {
      return virtualMemoryUsed_;
    }
    /**
     * <code>int64 virtualMemoryUsed = 5;</code>
     * @param value The virtualMemoryUsed to set.
     * @return This builder for chaining.
     */
    public Builder setVirtualMemoryUsed(long value) {

      virtualMemoryUsed_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 virtualMemoryUsed = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearVirtualMemoryUsed() {
      bitField0_ = (bitField0_ & ~0x00000010);
      virtualMemoryUsed_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.vlad.metrics.models.MemoryMetric)
  }

  // @@protoc_insertion_point(class_scope:com.vlad.metrics.models.MemoryMetric)
  private static final metrics.MemoryMetric DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new metrics.MemoryMetric();
  }

  public static metrics.MemoryMetric getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MemoryMetric>
      PARSER = new com.google.protobuf.AbstractParser<MemoryMetric>() {
    @java.lang.Override
    public MemoryMetric parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MemoryMetric> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MemoryMetric> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public metrics.MemoryMetric getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

