// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: metrics.proto
// Protobuf Java Version: 4.28.3

package metrics;

public final class Metrics {
  private Metrics() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      Metrics.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metrics_CpuMetric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_metrics_CpuMetric_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metrics_DiskMetric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_metrics_DiskMetric_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metrics_MemoryMetric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_metrics_MemoryMetric_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metrics_NetworkMetric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_metrics_NetworkMetric_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metrics_OsMetric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_metrics_OsMetric_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metrics_SensorMetric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_metrics_SensorMetric_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmetrics.proto\022\007metrics\"D\n\tCpuMetric\022\021\n" +
      "\ttotalLoad\030\001 \001(\001\022\021\n\tcoreLoads\030\002 \003(\001\022\021\n\tf" +
      "requency\030\003 \003(\003\"\247\001\n\nDiskMetric\022\020\n\010diskNam" +
      "e\030\001 \001(\t\022\021\n\tdiskReads\030\002 \001(\003\022\022\n\ndiskWrites" +
      "\030\003 \001(\003\022\025\n\rdiskReadBytes\030\004 \001(\003\022\026\n\016diskWri" +
      "teBytes\030\005 \001(\003\022\027\n\017diskQueueLength\030\006 \001(\003\022\030" +
      "\n\020diskTransferTime\030\007 \001(\003\"\223\001\n\014MemoryMetri" +
      "c\022\033\n\023totalPhysicalMemory\030\001 \001(\003\022\032\n\022usedPh" +
      "ysicalMemory\030\002 \001(\003\022\027\n\017totalSwapMemory\030\003 " +
      "\001(\003\022\026\n\016usedSwapMemory\030\004 \001(\003\022\031\n\021virtualMe" +
      "moryUsed\030\005 \001(\003\"\304\001\n\rNetworkMetric\022\014\n\004name" +
      "\030\001 \001(\t\022\023\n\013displayName\030\002 \001(\t\022\021\n\tbytesSent" +
      "\030\003 \001(\003\022\021\n\tbytesRecv\030\004 \001(\003\022\023\n\013packetsSent" +
      "\030\005 \001(\003\022\023\n\013packetsRecv\030\006 \001(\003\022\025\n\ripv4Addre" +
      "sses\030\007 \001(\t\022\025\n\ripv6Addresses\030\010 \001(\t\022\022\n\nmac" +
      "Address\030\t \001(\t\"O\n\010OsMetric\022\017\n\007os_name\030\001 \001" +
      "(\t\022\016\n\006uptime\030\002 \001(\003\022\021\n\tprocesses\030\003 \001(\005\022\017\n" +
      "\007threads\030\004 \001(\005\"M\n\014SensorMetric\022\026\n\016cpuTem" +
      "perature\030\001 \001(\001\022\021\n\tfanSpeeds\030\002 \003(\005\022\022\n\ncpu" +
      "Voltage\030\003 \001(\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_metrics_CpuMetric_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_metrics_CpuMetric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_metrics_CpuMetric_descriptor,
        new java.lang.String[] { "TotalLoad", "CoreLoads", "Frequency", });
    internal_static_metrics_DiskMetric_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_metrics_DiskMetric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_metrics_DiskMetric_descriptor,
        new java.lang.String[] { "DiskName", "DiskReads", "DiskWrites", "DiskReadBytes", "DiskWriteBytes", "DiskQueueLength", "DiskTransferTime", });
    internal_static_metrics_MemoryMetric_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_metrics_MemoryMetric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_metrics_MemoryMetric_descriptor,
        new java.lang.String[] { "TotalPhysicalMemory", "UsedPhysicalMemory", "TotalSwapMemory", "UsedSwapMemory", "VirtualMemoryUsed", });
    internal_static_metrics_NetworkMetric_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_metrics_NetworkMetric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_metrics_NetworkMetric_descriptor,
        new java.lang.String[] { "Name", "DisplayName", "BytesSent", "BytesRecv", "PacketsSent", "PacketsRecv", "Ipv4Addresses", "Ipv6Addresses", "MacAddress", });
    internal_static_metrics_OsMetric_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_metrics_OsMetric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_metrics_OsMetric_descriptor,
        new java.lang.String[] { "OsName", "Uptime", "Processes", "Threads", });
    internal_static_metrics_SensorMetric_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_metrics_SensorMetric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_metrics_SensorMetric_descriptor,
        new java.lang.String[] { "CpuTemperature", "FanSpeeds", "CpuVoltage", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
