// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: metrics.proto
// Protobuf Java Version: 4.28.3

package metrics;

/**
 * Protobuf type {@code com.vlad.metrics.models.NetworkMetric}
 */
public final class NetworkMetric extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.vlad.metrics.models.NetworkMetric)
    NetworkMetricOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      NetworkMetric.class.getName());
  }
  // Use NetworkMetric.newBuilder() to construct.
  private NetworkMetric(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private NetworkMetric() {
    name_ = "";
    displayName_ = "";
    ipv4Addresses_ = "";
    ipv6Addresses_ = "";
    macAddress_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return metrics.Metrics.internal_static_metrics_NetworkMetric_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return metrics.Metrics.internal_static_metrics_NetworkMetric_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            metrics.NetworkMetric.class, metrics.NetworkMetric.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYNAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object displayName_ = "";
  /**
   * <code>string displayName = 2;</code>
   * @return The displayName.
   */
  @java.lang.Override
  public java.lang.String getDisplayName() {
    java.lang.Object ref = displayName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayName_ = s;
      return s;
    }
  }
  /**
   * <code>string displayName = 2;</code>
   * @return The bytes for displayName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDisplayNameBytes() {
    java.lang.Object ref = displayName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BYTESSENT_FIELD_NUMBER = 3;
  private long bytesSent_ = 0L;
  /**
   * <code>int64 bytesSent = 3;</code>
   * @return The bytesSent.
   */
  @java.lang.Override
  public long getBytesSent() {
    return bytesSent_;
  }

  public static final int BYTESRECV_FIELD_NUMBER = 4;
  private long bytesRecv_ = 0L;
  /**
   * <code>int64 bytesRecv = 4;</code>
   * @return The bytesRecv.
   */
  @java.lang.Override
  public long getBytesRecv() {
    return bytesRecv_;
  }

  public static final int PACKETSSENT_FIELD_NUMBER = 5;
  private long packetsSent_ = 0L;
  /**
   * <code>int64 packetsSent = 5;</code>
   * @return The packetsSent.
   */
  @java.lang.Override
  public long getPacketsSent() {
    return packetsSent_;
  }

  public static final int PACKETSRECV_FIELD_NUMBER = 6;
  private long packetsRecv_ = 0L;
  /**
   * <code>int64 packetsRecv = 6;</code>
   * @return The packetsRecv.
   */
  @java.lang.Override
  public long getPacketsRecv() {
    return packetsRecv_;
  }

  public static final int IPV4ADDRESSES_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ipv4Addresses_ = "";
  /**
   * <code>string ipv4Addresses = 7;</code>
   * @return The ipv4Addresses.
   */
  @java.lang.Override
  public java.lang.String getIpv4Addresses() {
    java.lang.Object ref = ipv4Addresses_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ipv4Addresses_ = s;
      return s;
    }
  }
  /**
   * <code>string ipv4Addresses = 7;</code>
   * @return The bytes for ipv4Addresses.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIpv4AddressesBytes() {
    java.lang.Object ref = ipv4Addresses_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ipv4Addresses_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IPV6ADDRESSES_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ipv6Addresses_ = "";
  /**
   * <code>string ipv6Addresses = 8;</code>
   * @return The ipv6Addresses.
   */
  @java.lang.Override
  public java.lang.String getIpv6Addresses() {
    java.lang.Object ref = ipv6Addresses_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ipv6Addresses_ = s;
      return s;
    }
  }
  /**
   * <code>string ipv6Addresses = 8;</code>
   * @return The bytes for ipv6Addresses.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIpv6AddressesBytes() {
    java.lang.Object ref = ipv6Addresses_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ipv6Addresses_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MACADDRESS_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object macAddress_ = "";
  /**
   * <code>string macAddress = 9;</code>
   * @return The macAddress.
   */
  @java.lang.Override
  public java.lang.String getMacAddress() {
    java.lang.Object ref = macAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      macAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string macAddress = 9;</code>
   * @return The bytes for macAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMacAddressBytes() {
    java.lang.Object ref = macAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      macAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(displayName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, displayName_);
    }
    if (bytesSent_ != 0L) {
      output.writeInt64(3, bytesSent_);
    }
    if (bytesRecv_ != 0L) {
      output.writeInt64(4, bytesRecv_);
    }
    if (packetsSent_ != 0L) {
      output.writeInt64(5, packetsSent_);
    }
    if (packetsRecv_ != 0L) {
      output.writeInt64(6, packetsRecv_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ipv4Addresses_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, ipv4Addresses_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ipv6Addresses_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, ipv6Addresses_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(macAddress_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, macAddress_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(displayName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, displayName_);
    }
    if (bytesSent_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, bytesSent_);
    }
    if (bytesRecv_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, bytesRecv_);
    }
    if (packetsSent_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, packetsSent_);
    }
    if (packetsRecv_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, packetsRecv_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ipv4Addresses_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, ipv4Addresses_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ipv6Addresses_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, ipv6Addresses_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(macAddress_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, macAddress_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof metrics.NetworkMetric)) {
      return super.equals(obj);
    }
    metrics.NetworkMetric other = (metrics.NetworkMetric) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getDisplayName()
        .equals(other.getDisplayName())) return false;
    if (getBytesSent()
        != other.getBytesSent()) return false;
    if (getBytesRecv()
        != other.getBytesRecv()) return false;
    if (getPacketsSent()
        != other.getPacketsSent()) return false;
    if (getPacketsRecv()
        != other.getPacketsRecv()) return false;
    if (!getIpv4Addresses()
        .equals(other.getIpv4Addresses())) return false;
    if (!getIpv6Addresses()
        .equals(other.getIpv6Addresses())) return false;
    if (!getMacAddress()
        .equals(other.getMacAddress())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DISPLAYNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayName().hashCode();
    hash = (37 * hash) + BYTESSENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBytesSent());
    hash = (37 * hash) + BYTESRECV_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBytesRecv());
    hash = (37 * hash) + PACKETSSENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPacketsSent());
    hash = (37 * hash) + PACKETSRECV_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPacketsRecv());
    hash = (37 * hash) + IPV4ADDRESSES_FIELD_NUMBER;
    hash = (53 * hash) + getIpv4Addresses().hashCode();
    hash = (37 * hash) + IPV6ADDRESSES_FIELD_NUMBER;
    hash = (53 * hash) + getIpv6Addresses().hashCode();
    hash = (37 * hash) + MACADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getMacAddress().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static metrics.NetworkMetric parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static metrics.NetworkMetric parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static metrics.NetworkMetric parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static metrics.NetworkMetric parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static metrics.NetworkMetric parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static metrics.NetworkMetric parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static metrics.NetworkMetric parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static metrics.NetworkMetric parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static metrics.NetworkMetric parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static metrics.NetworkMetric parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static metrics.NetworkMetric parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static metrics.NetworkMetric parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(metrics.NetworkMetric prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.vlad.metrics.models.NetworkMetric}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.vlad.metrics.models.NetworkMetric)
      metrics.NetworkMetricOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return metrics.Metrics.internal_static_metrics_NetworkMetric_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return metrics.Metrics.internal_static_metrics_NetworkMetric_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              metrics.NetworkMetric.class, metrics.NetworkMetric.Builder.class);
    }

    // Construct using com.vlad.metrics.models.NetworkMetric.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      displayName_ = "";
      bytesSent_ = 0L;
      bytesRecv_ = 0L;
      packetsSent_ = 0L;
      packetsRecv_ = 0L;
      ipv4Addresses_ = "";
      ipv6Addresses_ = "";
      macAddress_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return metrics.Metrics.internal_static_metrics_NetworkMetric_descriptor;
    }

    @java.lang.Override
    public metrics.NetworkMetric getDefaultInstanceForType() {
      return metrics.NetworkMetric.getDefaultInstance();
    }

    @java.lang.Override
    public metrics.NetworkMetric build() {
      metrics.NetworkMetric result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public metrics.NetworkMetric buildPartial() {
      metrics.NetworkMetric result = new metrics.NetworkMetric(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(metrics.NetworkMetric result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.displayName_ = displayName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.bytesSent_ = bytesSent_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.bytesRecv_ = bytesRecv_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.packetsSent_ = packetsSent_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.packetsRecv_ = packetsRecv_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.ipv4Addresses_ = ipv4Addresses_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.ipv6Addresses_ = ipv6Addresses_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.macAddress_ = macAddress_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof metrics.NetworkMetric) {
        return mergeFrom((metrics.NetworkMetric)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(metrics.NetworkMetric other) {
      if (other == metrics.NetworkMetric.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDisplayName().isEmpty()) {
        displayName_ = other.displayName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getBytesSent() != 0L) {
        setBytesSent(other.getBytesSent());
      }
      if (other.getBytesRecv() != 0L) {
        setBytesRecv(other.getBytesRecv());
      }
      if (other.getPacketsSent() != 0L) {
        setPacketsSent(other.getPacketsSent());
      }
      if (other.getPacketsRecv() != 0L) {
        setPacketsRecv(other.getPacketsRecv());
      }
      if (!other.getIpv4Addresses().isEmpty()) {
        ipv4Addresses_ = other.ipv4Addresses_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getIpv6Addresses().isEmpty()) {
        ipv6Addresses_ = other.ipv6Addresses_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getMacAddress().isEmpty()) {
        macAddress_ = other.macAddress_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              displayName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              bytesSent_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              bytesRecv_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              packetsSent_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              packetsRecv_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              ipv4Addresses_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              ipv6Addresses_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              macAddress_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object displayName_ = "";
    /**
     * <code>string displayName = 2;</code>
     * @return The displayName.
     */
    public java.lang.String getDisplayName() {
      java.lang.Object ref = displayName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayName = 2;</code>
     * @return The bytes for displayName.
     */
    public com.google.protobuf.ByteString
        getDisplayNameBytes() {
      java.lang.Object ref = displayName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayName = 2;</code>
     * @param value The displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      displayName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string displayName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayName() {
      displayName_ = getDefaultInstance().getDisplayName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string displayName = 2;</code>
     * @param value The bytes for displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      displayName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long bytesSent_ ;
    /**
     * <code>int64 bytesSent = 3;</code>
     * @return The bytesSent.
     */
    @java.lang.Override
    public long getBytesSent() {
      return bytesSent_;
    }
    /**
     * <code>int64 bytesSent = 3;</code>
     * @param value The bytesSent to set.
     * @return This builder for chaining.
     */
    public Builder setBytesSent(long value) {

      bytesSent_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 bytesSent = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBytesSent() {
      bitField0_ = (bitField0_ & ~0x00000004);
      bytesSent_ = 0L;
      onChanged();
      return this;
    }

    private long bytesRecv_ ;
    /**
     * <code>int64 bytesRecv = 4;</code>
     * @return The bytesRecv.
     */
    @java.lang.Override
    public long getBytesRecv() {
      return bytesRecv_;
    }
    /**
     * <code>int64 bytesRecv = 4;</code>
     * @param value The bytesRecv to set.
     * @return This builder for chaining.
     */
    public Builder setBytesRecv(long value) {

      bytesRecv_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 bytesRecv = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBytesRecv() {
      bitField0_ = (bitField0_ & ~0x00000008);
      bytesRecv_ = 0L;
      onChanged();
      return this;
    }

    private long packetsSent_ ;
    /**
     * <code>int64 packetsSent = 5;</code>
     * @return The packetsSent.
     */
    @java.lang.Override
    public long getPacketsSent() {
      return packetsSent_;
    }
    /**
     * <code>int64 packetsSent = 5;</code>
     * @param value The packetsSent to set.
     * @return This builder for chaining.
     */
    public Builder setPacketsSent(long value) {

      packetsSent_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 packetsSent = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPacketsSent() {
      bitField0_ = (bitField0_ & ~0x00000010);
      packetsSent_ = 0L;
      onChanged();
      return this;
    }

    private long packetsRecv_ ;
    /**
     * <code>int64 packetsRecv = 6;</code>
     * @return The packetsRecv.
     */
    @java.lang.Override
    public long getPacketsRecv() {
      return packetsRecv_;
    }
    /**
     * <code>int64 packetsRecv = 6;</code>
     * @param value The packetsRecv to set.
     * @return This builder for chaining.
     */
    public Builder setPacketsRecv(long value) {

      packetsRecv_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 packetsRecv = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPacketsRecv() {
      bitField0_ = (bitField0_ & ~0x00000020);
      packetsRecv_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object ipv4Addresses_ = "";
    /**
     * <code>string ipv4Addresses = 7;</code>
     * @return The ipv4Addresses.
     */
    public java.lang.String getIpv4Addresses() {
      java.lang.Object ref = ipv4Addresses_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipv4Addresses_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ipv4Addresses = 7;</code>
     * @return The bytes for ipv4Addresses.
     */
    public com.google.protobuf.ByteString
        getIpv4AddressesBytes() {
      java.lang.Object ref = ipv4Addresses_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipv4Addresses_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ipv4Addresses = 7;</code>
     * @param value The ipv4Addresses to set.
     * @return This builder for chaining.
     */
    public Builder setIpv4Addresses(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ipv4Addresses_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string ipv4Addresses = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearIpv4Addresses() {
      ipv4Addresses_ = getDefaultInstance().getIpv4Addresses();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string ipv4Addresses = 7;</code>
     * @param value The bytes for ipv4Addresses to set.
     * @return This builder for chaining.
     */
    public Builder setIpv4AddressesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ipv4Addresses_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object ipv6Addresses_ = "";
    /**
     * <code>string ipv6Addresses = 8;</code>
     * @return The ipv6Addresses.
     */
    public java.lang.String getIpv6Addresses() {
      java.lang.Object ref = ipv6Addresses_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipv6Addresses_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ipv6Addresses = 8;</code>
     * @return The bytes for ipv6Addresses.
     */
    public com.google.protobuf.ByteString
        getIpv6AddressesBytes() {
      java.lang.Object ref = ipv6Addresses_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipv6Addresses_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ipv6Addresses = 8;</code>
     * @param value The ipv6Addresses to set.
     * @return This builder for chaining.
     */
    public Builder setIpv6Addresses(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ipv6Addresses_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string ipv6Addresses = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearIpv6Addresses() {
      ipv6Addresses_ = getDefaultInstance().getIpv6Addresses();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string ipv6Addresses = 8;</code>
     * @param value The bytes for ipv6Addresses to set.
     * @return This builder for chaining.
     */
    public Builder setIpv6AddressesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ipv6Addresses_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object macAddress_ = "";
    /**
     * <code>string macAddress = 9;</code>
     * @return The macAddress.
     */
    public java.lang.String getMacAddress() {
      java.lang.Object ref = macAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        macAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string macAddress = 9;</code>
     * @return The bytes for macAddress.
     */
    public com.google.protobuf.ByteString
        getMacAddressBytes() {
      java.lang.Object ref = macAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        macAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string macAddress = 9;</code>
     * @param value The macAddress to set.
     * @return This builder for chaining.
     */
    public Builder setMacAddress(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      macAddress_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string macAddress = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearMacAddress() {
      macAddress_ = getDefaultInstance().getMacAddress();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string macAddress = 9;</code>
     * @param value The bytes for macAddress to set.
     * @return This builder for chaining.
     */
    public Builder setMacAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      macAddress_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.vlad.metrics.models.NetworkMetric)
  }

  // @@protoc_insertion_point(class_scope:com.vlad.metrics.models.NetworkMetric)
  private static final metrics.NetworkMetric DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new metrics.NetworkMetric();
  }

  public static metrics.NetworkMetric getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NetworkMetric>
      PARSER = new com.google.protobuf.AbstractParser<NetworkMetric>() {
    @java.lang.Override
    public NetworkMetric parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NetworkMetric> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NetworkMetric> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public metrics.NetworkMetric getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

