// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: metrics.proto
// Protobuf Java Version: 4.28.3

package metrics;

public interface SensorMetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vlad.metrics.models.SensorMetric)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double cpuTemperature = 1;</code>
   * @return The cpuTemperature.
   */
  double getCpuTemperature();

  /**
   * <code>repeated int32 fanSpeeds = 2;</code>
   * @return A list containing the fanSpeeds.
   */
  java.util.List<java.lang.Integer> getFanSpeedsList();
  /**
   * <code>repeated int32 fanSpeeds = 2;</code>
   * @return The count of fanSpeeds.
   */
  int getFanSpeedsCount();
  /**
   * <code>repeated int32 fanSpeeds = 2;</code>
   * @param index The index of the element to return.
   * @return The fanSpeeds at the given index.
   */
  int getFanSpeeds(int index);

  /**
   * <code>double cpuVoltage = 3;</code>
   * @return The cpuVoltage.
   */
  double getCpuVoltage();
}
