// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: metrics.proto
// Protobuf Java Version: 4.28.3

package com.vlad.metrics.models;

public interface NetworkMetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.vlad.metrics.models.NetworkMetric)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string displayName = 2;</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <code>string displayName = 2;</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <code>int64 bytesSent = 3;</code>
   * @return The bytesSent.
   */
  long getBytesSent();

  /**
   * <code>int64 bytesRecv = 4;</code>
   * @return The bytesRecv.
   */
  long getBytesRecv();

  /**
   * <code>int64 packetsSent = 5;</code>
   * @return The packetsSent.
   */
  long getPacketsSent();

  /**
   * <code>int64 packetsRecv = 6;</code>
   * @return The packetsRecv.
   */
  long getPacketsRecv();

  /**
   * <code>repeated string ipv4Addresses = 7;</code>
   * @return A list containing the ipv4Addresses.
   */
  java.util.List<java.lang.String>
      getIpv4AddressesList();
  /**
   * <code>repeated string ipv4Addresses = 7;</code>
   * @return The count of ipv4Addresses.
   */
  int getIpv4AddressesCount();
  /**
   * <code>repeated string ipv4Addresses = 7;</code>
   * @param index The index of the element to return.
   * @return The ipv4Addresses at the given index.
   */
  java.lang.String getIpv4Addresses(int index);
  /**
   * <code>repeated string ipv4Addresses = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the ipv4Addresses at the given index.
   */
  com.google.protobuf.ByteString
      getIpv4AddressesBytes(int index);

  /**
   * <code>repeated string ipv6Addresses = 8;</code>
   * @return A list containing the ipv6Addresses.
   */
  java.util.List<java.lang.String>
      getIpv6AddressesList();
  /**
   * <code>repeated string ipv6Addresses = 8;</code>
   * @return The count of ipv6Addresses.
   */
  int getIpv6AddressesCount();
  /**
   * <code>repeated string ipv6Addresses = 8;</code>
   * @param index The index of the element to return.
   * @return The ipv6Addresses at the given index.
   */
  java.lang.String getIpv6Addresses(int index);
  /**
   * <code>repeated string ipv6Addresses = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the ipv6Addresses at the given index.
   */
  com.google.protobuf.ByteString
      getIpv6AddressesBytes(int index);

  /**
   * <code>string macAddress = 9;</code>
   * @return The macAddress.
   */
  java.lang.String getMacAddress();
  /**
   * <code>string macAddress = 9;</code>
   * @return The bytes for macAddress.
   */
  com.google.protobuf.ByteString
      getMacAddressBytes();
}
